### PR TITLE
Dota2 Api

### PR DESCRIPTION
**Pull request by Pazus**
Added Dota 2 API methods based on [https://wiki.teamfortress.com/wiki/WebAPI#Dota_2](https://wiki.teamfortress.com/wiki/WebAPI#Dota_2).

This is my first pull request so please guide me a bit.

### CODE REVIEW

**Comment by lpradel** [comment]
Hi Pazus, thanks a lot! As your changes are quite substantial, please allow me a few days to look through them.

**Comment by Pazus** [comment]
I'm not sure, dose Travis error caused by my changes?

**Comment by lpradel** [comment]
Could you please rename the directory

`src/main/resources/com/lukaspradel/steamapi/schema/Dota2/`

to

`src/main/resources/com/lukaspradel/steamapi/schema/dota2/`

I suspect that the capital 'D' may throw off Travis here. Building your branch worked on my machine.

**Comment by Pazus** [comment]
Sorry for the trully long responce

**Comment by Pazus** [comment]
Could you please look at the error in Travis.

**Comment by lpradel** [comment]
I'm pretty sure the error in Travis is actually a Travis bug. Thank you for your work, feel free to keep contributing!

**Comment by lpradel** [comment]
Also, let me know when you are done with this feature because I want to build a major release shortly after.

**Comment by Pazus** [comment]
Could you restart the build to check if its Travis bug?

**Comment by lpradel** [comment]
It works now: https://travis-ci.org/lpradel/steam-web-api-java/builds/185827894

Are you done with this feature?

**Comment by Pazus** [comment]
At least I'm not going to add new things to it :)

**Comment by lpradel** [comment]
Thank you for all your work on this!  I will release a new major version with it soon.

**Pull request merged**
