### PR TITLE
Exclude schema files, when packaging the jar

### PR DESCRIPTION
**Pull request by 41zu**
This saves 15.7 kb of file size

### CODE REVIEW

**Comment by lpradel** [comment]
Makes sense, thank you!

**Comment by 41zu** [comment]
@lpradel Thank you for merging! Could you please release version 1.8.0 to maven when your time allows?

**Comment by lpradel** [comment]
@41zu It's on Maven Central now!

**Comment by 41zu** [comment]
@lpradel Thank you!

**Pull request merged**
