### PR TITLE
Add support for /ISteamApps/GetAppList/v0002/

### PR DESCRIPTION
**Pull request by josephbleau**
Hello! Thanks for the really easy to use and extend API library! :)

### Change Description
This small change adds support for the GetAppList API call.
- This API is available without key, seen here: http://api.steampowered.com/ISteamApps/GetAppList/v0002/
- See also: https://partner.steamgames.com/doc/webapi/ISteamApps#GetAppList

This API is useful for applications that want to interact with other APIs such as [GetAppDetails](https://store.steampowered.com/api/appdetails?appids=2222830), where an AppID is expected.

### CODE REVIEW

**Comment by lpradel** [comment]
Hi Joey,

thanks a lot for your contribution! I'm leaving for vacation today so unfortunately I can't review this in time anymore. Promise to look at it when I get back middle of June. Once again, thanks for your patience.

**Comment by josephbleau** [comment]
No worries, it is of extremely low importance. Enjoy your trip!

**Comment by lpradel** [comment]
@josephbleau Overall your changes are good, thanks! However there's a few bits and pieces missing (mostly tests) before I can integrate your changes. I have prepared the additional changes in the branch of your fork. Could you grant me permission to push changes into the branch of your fork? [If you are not sure how, here is the doc](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by lpradel** [comment]
Actually never mind that it seems it was enabled by default. Please review the [changes I amended to your original PR](https://github.com/lpradel/steam-web-api-java/pull/22/commits/1aeb7f29fe07a05bacae76a2d0fd9ad8d625a23c):

**Comment by lpradel** [comment]
I will release as 1.6.0 ASAP thanks for your help!

**Pull request merged**
